INSERT INTO CardStacks(cardStackName, isDefaultCardStack) VALUES('Części ciała',1);
INSERT INTO CardStacks(cardStackName, isDefaultCardStack) VALUES('Czynności',1);
INSERT INTO CardStacks(cardStackName, isDefaultCardStack) VALUES('Jedzenie i picie',1);
INSERT INTO CardStacks(cardStackName, isDefaultCardStack) VALUES('Kolory',1);
INSERT INTO CardStacks(cardStackName, isDefaultCardStack) VALUES('Miejsce zamieszkania',1);
INSERT INTO CardStacks(cardStackName, isDefaultCardStack) VALUES('Natura',1);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('głowa','head',1);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('ucho','ear',1);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('oko','eye',1);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('nos','nose',1);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('usta','mouth',1);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('gardło','throat',1);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('ręka','arm',1);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('noga','leg',1);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('dłoń','hand',1);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('palec','finger',1);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('stopa','foot',1);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('plecy','back',1);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('klatka piersiowa','chest',1);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('kręgosłup','spine',1);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('jeść','eat',2);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('spać','sleep',2);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('patrzeć','look',2);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('dotykać','touch',2);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('uśmiechać się','smile',2);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('iść','walk',2);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('biec','run',2);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('pisać','write',2);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('pisać na klawiaturze','type',2);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('czytać','read',2);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('ćwiczyć','exercise',2);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('rysować','draw',2);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('mówić','speak',2);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('słuchać','listen',2);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('grać','play',2);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('śpiewać','sing',2);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('warzywa','vegetables',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('owoce','fruits',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('chleb','bread',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('mięso','meat',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('ryba','fish',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('ser','cheese',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('ryż','rice',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('jajko','egg',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('cukier','sugar',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('lody','ice cream',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('czekolada','chocolate',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('ciastko','biscuit',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('cukierek','candy',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('napój','drink',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('woda','water',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('mleko','milk',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('kawa','coffee',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('herbata','tea',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('sok','juice',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('napój gazowany','fizzy drink',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('piwo','beer',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('wino','wine',3);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('różowy','pink',4);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('czerwony','red',4);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('pomarańczowy','orange',4);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('żółty','yellow',4);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('zielony','green',4);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('niebieski','blue',4);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('fioletowy','purple',4);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('biały','white',4);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('czarny','black',4);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('brązowy','brown',4);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('szary','grey',4);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('beżowy','beige',4);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('ciemnoniebieski','dark blue',4);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('jasnoniebieski','light blue',4);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('brama','gate',5);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('drzwi wejściowe','front door',5);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('schody','stairs',5);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('balkon','balcony',5);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('salon','living room',5);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('okno','window',5);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('łazienka','bathroom',5);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('jadalnia','dining room',5);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('sypialnia','bedroom',5);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('kuchnia','kitchen',5);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('ściana','wall',5);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('podłoga','floor',5);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('dywan','carpet',5);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('sufit','ceiling',5);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('światło','light',5);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('włącznik','switch',5);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('gniazdko','socket',5);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('kaloryfer','radiator',5);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('roślina','plant',6);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('kwiat','flower',6);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('las','forest',6);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('drzewo','tree',6);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('krzak','bush',6);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('trawa','grass',6);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('góra','mountain',6);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('skała','rock',6);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('wyspa','island',6);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('morze','sea',6);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('rzeka','river',6);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('jezioro','lake',6);
INSERT INTO Words(wordPolish, WordTranslated, cardStackId) VALUES('staw','pond',6);
